theme = "dark_high_contrast"

[editor]
line-number = "relative"
mouse = false
true-color = true
clipboard-provider = "tmux"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
